name: CI Build

on:
  push:
    paths-ignore:
      - "**.md"
      - "COPYING"

jobs:
  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: binary.darwin
          path: |
            build.log
            backend/target/release/mpdweb

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: make
      - uses: actions/upload-artifact@v3
        with:
          name: binary.linux
          path: |
            build.log
            backend/target/release/mpdweb
